### ISSUE TITLE
scrollToPosition breaks the code!

### ISSUE THREAD

**Issue by totomft1518** [delaroy/Carousel#1]
Hi there,

I have to dynamically scroll the recycler view to a given positon, unlikely when i use rv.scrollToPosition(givenPosition) the app crashes.
Following the error : " Caused by: kotlin.UninitializedPropertyAccessException: lateinit property recycler has not been initialized at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager.scrollToPosition(CarouselLayoutManager.kt:404)".

Really hope someone out there can help me. Thanks a lot

**Comment by nicholasedgetech** [comment]
> Hi there,
> 
> I have to dynamically scroll the recycler view to a given positon, unlikely when i use rv.scrollToPosition(givenPosition) the app crashes. Following the error : " Caused by: kotlin.UninitializedPropertyAccessException: lateinit property recycler has not been initialized at com.jackandphantom.carouselrecyclerview.CarouselLayoutManager.scrollToPosition(CarouselLayoutManager.kt:404)".
> 
> Really hope someone out there can help me. Thanks a lot

I have facing same issue while I'm using rv.smoothScrollToPosition(givenPosition). But I did a tricky way to overcome this issue by:

rv.viewTreeObserver.addOnGlobalLayoutListener {
    rv.smoothScrollToPosition(givenPosition)
}
Hope this might help!
